socketjet_web/dashboard/urls.py
from django.conf.urls.defaults import patterns, include, url  

urlpatterns = patterns('dashboard.views',
    (r'^$', 'sites_list'),
    url(r'^channels/$', 'channels_list', name='channels_list'), 
    url(r'^channels/edit/(?P<channel_id>\d+)/$', 'channels_edit', name='channels_edit'),
    url(r'^channels/add/$', 'channels_add', name='channels_add'),
    url(r'^channels/delete/(?P<channel_id>\d+)/$', 'channels_delete', name='channels_delete'),
    url(r'^sites/$', 'sites_list', name='sites_list'),
    url(r'^sites/edit/(?P<site_id>\d+)/$', 'sites_edit', name='sites_edit'),
    url(r'^sites/add/$', 'sites_add', name='sites_add'),
    url(r'^sites/delete/(?P<site_id>\d+)/$', 'sites_delete', name='sites_delete'),
)

socketjet_web/urls.py
from django.conf.urls.defaults import patterns, include, url
                                                    
from django.contrib import admin
admin.autodiscover() 

from django.conf import settings

urlpatterns = patterns('',                     
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^app/', include('clients.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^', include('common.urls')),
) 

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

socketjet_web/common/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid  

def upload_location(instance, filename):
    return 'user_data/%s/%s' % (instance.api_key, filename)

class ApiCreationException(Exception):
    pass   
    
class AccountManager(models.Manager):
    def create_account(self, user, site_prefix):
        api_key = ApiAccount.create_api_key()
        secret_key = ApiAccount.create_api_key()
        api_account = self.create(api_key=api_key, user=user, secret_key=secret_key, site_prefix=site_prefix)
        
        # also create a client user perm for this account
        user_perm = ClientUserPermissions.objects.create(client_user=user, api_account=api_account, is_admin=True)
        
        return api_account, user_perm 
                                          
class ActiveAccountManager(models.Manager):
    def get_query_set(self):
        return super(ActiveAccountManager, self).get_query_set().filter(disabled=False)                

class ApiAccount(models.Model): 
    site_prefix = models.CharField(max_length=50, unique=True, help_text='also the app name')
    api_key = models.CharField(max_length=50, db_index=True)
    user = models.ForeignKey(User)             
    created = models.DateTimeField(auto_now_add=True) 
    secret_key = models.CharField(max_length=50)
    callback_url = models.URLField(blank=True, null=True)
    disabled = models.BooleanField(default=False)
            
    objects = AccountManager()
    active_objects = ActiveAccountManager()
                                                  
    def __unicode__(self):
        return self.site_prefix
        
    class Meta:
        verbose_name_plural = 'Sites (Api Accounts)'
        verbose_name = 'Site'
        
    @staticmethod
    def create_api_key():
        for i in xrange(1000):
            api_key = ''.join(str(uuid.uuid4()).split('-'))
            if ApiAccount.objects.filter(api_key=api_key).count() == 0:
                return api_key
                
        raise ApiCreationException 
        
class UserCreatedChannel(models.Model):
    channel_name = models.CharField(max_length=100)  
    created_by = models.ForeignKey(User)
    site = models.ForeignKey(ApiAccount)   
    
    def __unicode__(self):
        return self.channel_name
        
    class Meta:
        verbose_name_plural = 'User Created Channels'
        unique_together = ('channel_name', 'created_by', 'site')
        
class ClientUserPermissions(models.Model):
    client_user = models.ForeignKey(User)
    api_account = models.ForeignKey(ApiAccount)
    db_del = models.BooleanField(default=False)
    private_channels = models.ManyToManyField(UserCreatedChannel, blank=True, null=True)
    is_admin = models.BooleanField(default=False)
    
    def __unicode__(self):
        return '%s: %s' % (self.client_user.username, self.api_account.site_prefix)
        
    class Meta:
        verbose_name_plural = 'Client User Permissions'   
        
class AccountPackage(models.Model):
    name = models.CharField(max_length=100)
    max_connections = models.IntegerField(help_text="simultaneous connections")
    max_messages = models.IntegerField(help_text="max messages per day")
    is_starter = models.BooleanField(default=False)  

    def __unicode__(self):
        return self.name      
        
def get_auth_token():
    return AccountUserProfile.create_auth_token()
        
class AccountUserProfile(models.Model):
    user = models.OneToOneField(User)
    current_monthly_messages = models.IntegerField(default=0) 
    account_package = models.ForeignKey(AccountPackage) 
    auth_token = models.CharField(max_length=100, blank=True, default=get_auth_token)
    is_verified = models.BooleanField(default=False)
    
    def __unicode__(self):
        return self.user.username 
        
    @staticmethod
    def create_auth_token():
        for i in xrange(1000):
            auth_token = ''.join(str(uuid.uuid4()).split('-'))
            if AccountUserProfile.objects.filter(auth_token=auth_token).count() == 0:
                return auth_token

        raise ApiCreationException   
        
        
class UserProfile(models.Model):  
    user = models.OneToOneField(User)
    account_created = models.DateTimeField(auto_now_add=True)   
    api_account = models.ForeignKey(ApiAccount)
    
    def __unicode__(self):
        return self.user.username  
        
class UsageTransaction(models.Model):     
    api_account = models.ForeignKey(ApiAccount)
    created = models.DateTimeField(auto_now_add=True)
    messages = models.IntegerField(default=0)
    connections = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.api_account.site_prefix
        
    class Meta:
        verbose_name_plural = 'Usage Transactions'

socketjet_web/dashboard/models.py
from django.db import models

# Create your models here.

socketjet_web/dashboard/forms.py
from django import forms
from django.forms import ModelForm

from common.models import ApiAccount, UserCreatedChannel      
        
class SiteForm(ModelForm):                   
    class Meta:
        model = ApiAccount
        fields = ('site_prefix',)
    
    def __init__(self, user, *args, **kwargs):    
        super(SiteForm, self).__init__(*args, **kwargs)
        
        self.user = user         
            
class ChannelForm(ModelForm):
    class Meta:
        model = UserCreatedChannel
        exclude = ('created_by')

socketjet_web/dashboard/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext 
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse 
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, Http404 
from django.contrib import messages 
from django.db.models import Sum  
from django.forms.util import ErrorList 

from common.models import ApiAccount, UserCreatedChannel, UsageTransaction, ClientUserPermissions 
from dashboard.forms import SiteForm, ChannelForm  

import datetime
from datetime import timedelta 
import os

class SpanErrorList(ErrorList):
    def __unicode__(self):
        return self.as_spans()
    def as_spans(self):
        if not self: return u''
        return u'%s' % ''.join([u'<span class="help-inline">%s</span>' % e for e in self])

@login_required(login_url='/accounts/login/')
def sites_list(request): 
    api_accounts = ApiAccount.active_objects.filter(user=request.user).order_by('site_prefix')
    accounts = []
    for a in api_accounts:
        data = {}
        data['api_key'] = a.api_key
        data['site_prefix'] = a.site_prefix 
        data['id'] = a.id
        trans = a.usagetransaction_set.filter(created__gte=datetime.datetime.today().date()-timedelta(days=30))
        try:
            data['messages'] = trans.aggregate(messages=Sum('messages'))['messages'] / 30
        except:
            data['messages'] = 0
            
        try:
            data['connections'] = trans.aggregate(connections=Sum('connections'))['connections'] / 30
        except:
            data['connections'] = 0
            
        accounts.append(data)
             
    return render_to_response('sites_list.html', {'accounts':accounts
                                                      }, context_instance=RequestContext(request))

@login_required(login_url='/accounts/login/')
def sites_edit(request, site_id):
    site = get_object_or_404(ApiAccount, pk=site_id, disabled=False)
    if not site.user == request.user:
        raise Http404()
               
    error = None
    
    if request.method == 'POST':
        form = SiteForm(request.user, request.POST, error_class=SpanErrorList, instance=site)
        if form.is_valid():
            form.save()    
            messages.success(request, "Your site '%s' was saved." % site.site_prefix)
            return HttpResponseRedirect(reverse('sites_list'))
    else: 
        form = SiteForm(request.user, initial={'site_prefix':site.site_prefix}, instance=site)
             
    return render_to_response('sites_edit.html', {'form':form,
                                                  'site':site,         }, 
                                context_instance=RequestContext(request))
                                
@login_required(login_url="/accounts/login/")
def sites_add(request):
    if request.method == 'POST':
        form = SiteForm(request.user, request.POST, request.FILES, error_class=SpanErrorList)
        if form.is_valid(): 
            acc = form.save(commit=False)
            api_key = ApiAccount.create_api_key()
            secret_key = ApiAccount.create_api_key()
            acc.api_key = api_key
            acc.secret_key = secret_key 
            acc.user = request.user   
            acc.save()
            user_perm = ClientUserPermissions.objects.create(client_user=request.user, api_account=acc, is_admin=True)
              
            messages.success(request, "Your site '%s' was added." % form.cleaned_data['site_prefix'])
            return HttpResponseRedirect(reverse('sites_list'))
    else:                                       
        form = SiteForm(request.user)
             
    return render_to_response('sites_add.html', {'form':form}, context_instance=RequestContext(request))
    
@login_required(login_url="/accounts/login/")
def sites_delete(request, site_id):
    site = get_object_or_404(ApiAccount, pk=site_id, disabled=False)
    if not site.user == request.user:
        raise Http404()
                                    
    site.disabled = True
    site.save()
    messages.success(request, "Your site '%s' has been deleted." % site.site_prefix)
    return HttpResponseRedirect(reverse('sites_list'))
    
    
@login_required(login_url='/accounts/login/')
def channels_list(request):
    channels = request.user.usercreatedchannel_set.all().order_by('site__site_prefix')
    return render_to_response('channels_list.html', {'channels':channels},
                                context_instance=RequestContext(request))  

@login_required(login_url='/accounts/login/')                                
def channels_edit(request, channel_id):
    channel = get_object_or_404(UserCreatedChannel, pk=channel_id)
    if not channel.created_by == request.user:
        raise Http404 
        
    if request.method == 'POST':
        form = ChannelForm(request.POST, error_class=SpanErrorList, instance=channel)
        if form.is_valid():
            chan_form = form.save(commit=False)
            chan_form.created_by = request.user
            chan_form.save() 
            messages.success(request, "Your channel '%s' was saved." % form.cleaned_data['channel_name'])
            return HttpResponseRedirect(reverse('channels_list'))
    else:
        form = ChannelForm(instance=channel)
    
    form.fields['site'].queryset = ApiAccount.objects.filter(user=request.user)
        
    return render_to_response('channels_edit.html', {'form':form},
                                                    context_instance=RequestContext(request)) 
                                                    
@login_required(login_url='/accounts/login/')
def channels_add(request):
    if request.method == 'POST':
        form = ChannelForm(request.POST, error_class=SpanErrorList)
        if form.is_valid():
            chan_form = form.save(commit=False)
            chan_form.created_by = request.user
            chan_form.save()
            messages.success(request, "Your channel '%s' was added." % form.cleaned_data['channel_name'])
            return HttpResponseRedirect(reverse('channels_list'))
    else:
        form = ChannelForm()
    
    form.fields['site'].queryset = ApiAccount.objects.filter(user=request.user)
        
    return render_to_response('channels_add.html', {'form':form},
                                                    context_instance=RequestContext(request)) 
                                                    
@login_required(login_url='/accounts/login/') 
def channels_delete(request, channel_id):
    channel = get_object_or_404(UserCreatedChannel, pk=channel_id)
    if not channel.created_by == request.user:
        raise Http404
    
    name = channel.channel_name    
    channel.delete()
    messages.success(request, "Your channel '%s' has been deleted." % name)
    return HttpResponseRedirect(reverse('channels_list')) 
                

socketjet_web/dashboard/templates/channels_add.html
{% extends 'dashboard_base.html' %}   

{% block main_content %}
	<div class="row">
		<div class="span12"> 
			<ul class="nav pills">
				<li><a href="{% url sites_list %}">Sites</a></li>
				<li class="active"><a href="{% url channels_list %}">Channels</a></li>
				<li><a href="">Users</a></li>
			</ul>
            <ul class="breadcrumb">
				<li><a href="/dashboard/sites/">List channels</a> <span class="divider">/</span></li>
				<li class="active"><strong>Add channel</strong></li>
			</ul>
			
			<h2 class="page-header">Add Channel</h2>      

			<form action="." method="POST" class="form-horizontal">{% csrf_token %}
				<div class="control-group {% if form.channel_name.errors %}error{% endif %}">
	               	<label for="id_channel_name">{{ form.channel_name.label }}</label>
					<div class="controls">
						{{ form.channel_name }} 
						{{ form.channel_name.errors|safe }}
					</div>  
				</div>  
				
				<div class="control-group {% if form.site.errors %}error{% endif %}">
	               	<label for="id_site">{{ form.site.label }}</label>
					<div class="controls"> 
						{{ form.site }} {{ form.site.errors|safe }}
					</div>  
				</div>          
				          
				<div class="form-actions">
	            	<button type="submit" class="btn primary">Create site</button>  
				</div>
				
			</form>                
		</div>
	</div>
{% endblock %}

socketjet_web/dashboard/templates/channels_edit.html
{% extends 'dashboard_base.html' %}
                                  
{% block main_content %}
	<div class="row">
		<div class="span12"> 
			<ul class="nav pills">
				<li><a href="{% url sites_list %}">Sites</a></li>
				<li class="active"><a href="{% url channels_list %}">Channels</a></li>
				<li><a href="">Users</a></li>
			</ul>
            <ul class="breadcrumb">
				<li><a href="/dashboard/channels/">List channels</a> <span class="divider">/</span></li>
				<li class="active"><strong>Edit channel</strong></li>
			</ul>
			
			<h2 class="page-header">Edit Channel</h2>        

			<form action="." method="POST" class="form-horizontal">{% csrf_token %}
				<div class="control-group {% if form.channel_name.errors %}error{% endif %}">
	               	<label for="id_channel_name">{{ form.channel_name.label }}</label>
					<div class="controls">
						{{ form.channel_name }} 
						{{ form.channel_name.errors|safe }}
					</div>  
				</div>  
				
				<div class="control-group {% if form.site.errors %}error{% endif %}">
	               	<label for="id_site">{{ form.site.label }}</label>
					<div class="controls">    
						{{ form.site }} {{ form.site.errors|safe }} 
					</div>  
				</div>
				             
				<div class="form-actions">
	            	<button type="submit" class="btn primary">Save changes</button>  
				</div>
				
			</form>                
		</div>
	</div>
{% endblock %}

socketjet_web/dashboard/templates/channels_list.html
{% extends "dashboard_base.html" %} 

{% block script %}
	{{ block.super }}
	<script type="text/javascript">  
		$(document).ready(function() {
			$('.delete').click(function() {    
				$('#del_btn').attr('href', '/dashboard/channels/delete/' + this.id + '/');
				$('#delete-modal').modal('show');
				return false;
			});
		});
	</script>
{% endblock %}
                                 
{% block main_content %}
	
	<div class="row">  
		<div class="span12">
			<ul class="nav pills">
				<li><a href="{% url sites_list %}">Sites</a></li>
				<li class="active"><a href="{% url channels_list %}">Channels</a></li>
				<li><a href="">Users</a></li>
			</ul> 
			
			{% if messages %}
				{% for message in messages %}
				 	<div class="alert alert-success">
						<a class="close" data-dismiss="alert">&times;</a>
						<strong>Success!</strong>
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			
			<h2 class="page-header">Private Channels</h2>
			<a href="/dashboard/channels/add/" class="btn"><i class="plus"></i> Add new channel</a>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Channel name</th>
						<th>Site</th> 
						<th>Actions</th>
					</tr>
				</thead>
				<tbody> 
					{% if channels %}
						{% for c in channels %}
							<tr>
								<td>{{ c.channel_name }}</td> 
								<td>{{ c.site.site_prefix }}</td>   
								<td><a href="/dashboard/channels/edit/{{ c.id }}/">edit</a>&nbsp;&nbsp;
									<a href="" class="delete" id="{{ c.id }}">delete</a></td>
							</tr> 
						{% endfor %}
					{% else %}
					 	<tr>
							<td colspan="2">No channels have been created</td>
						</tr>
					{% endif %}
				</tbody>
			</table>                                                        
		</div>
	</div>        
	
	<div class="modal fade hide" id="delete-modal">
	  <div class="modal-header">
	    <a class="close" data-dismiss="modal">×</a>
	    <h3>Are you sure you want to delete this channel?</h3>
	  </div>
	  <div class="modal-body">
	    <p>This may affect your application if it relies on this channel for private communications.</p>
	  </div>
	  <div class="modal-footer">
	    <a href="#" class="btn danger" id="del_btn">Delete channel</a>
	    <a href="#" class="btn" data-dismiss="modal">Close</a>
	  </div>
	</div>
{% endblock main_content %}

socketjet_web/dashboard/templates/dashboard_base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}{% endblock title %}</title>
		<!-- HTML5 shim, for IE6-8 support of HTML elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]--> 
	  	<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css" />    
	</head>
	<body style="padding-top: 50px">
		<div class="navbar navbar-fixed">
			<div class="navbar-inner">
				<div class="container"> 
					<a class="brand" href="/dashboard/">SocketJet</a>
					<ul class="nav">
						<li><a href="/dashboard/">Dashboard</a></li>
						<li><a href="/dashboard/sites/">Sites</a></li>           
					</ul>
					{% if user.is_authenticated %}  
					<ul class="nav pull-right">
					  <li class="dropdown">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					          {{ user.username }}
					      	<b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu">
					      <li><a href="/accounts/myaccount/">My Account</a></li>
						  <li><a href="/accounts/logout/">Log out</a></li>
					    </ul>           
					  </li>
					</ul>
					{% endif %} 				
				</div>
			</div>
		</div>
		
		<div class="container">
			{% block main_content %}
			{% endblock main_content %}
		</div>
		
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
		{% block script %}
			
		{% endblock %}
	</body>
</html>	
				   

socketjet_web/dashboard/templates/sites_add.html
{% extends 'dashboard_base.html' %}   

{% block main_content %}
	<div class="row">
		<div class="span12"> 
            <ul class="breadcrumb">
				<li><a href="/dashboard/sites/">List sites</a> <span class="divider">/</span></li>
				<li class="active"><strong>Add site</strong></li>
			</ul>
			
			<h2 class="page-header">Add Site</h2>      

			<form action="." method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
				<div class="control-group {% if form.site_prefix.errors %}error{% endif %}">
	               	<label for="id_site_prefix">{{ form.site_prefix.label }}</label>
					<div class="controls">
						{{ form.site_prefix }} 
						{{ form.site_prefix.errors|safe }}
					</div>  
				</div>  
				
				<div class="control-group {% if form.html_file.errors %}error{% endif %}">
	               	<label for="id_html_file">{{ form.html_file.label }}</label>
					<div class="controls"> 
						{{ form.html_file }} {{ form.html_file.errors|safe }}
					</div>  
				</div>
				
				<div class="control-group {% if form.logo.errors %}error{% endif %}">
	               	<label for="id_site_prefix">{{ form.logo.label }}</label>
					<div class="controls">   
						{{ form.logo }} {{ form.logo.errors|safe }}  
					</div>  
				</div>
				
				<div class="control-group {% if form.background_image.errors %}error{% endif %}">
	               	<label for="id_background_image">{{ form.background_image.label }}</label>
					<div class="controls">    
						{{ form.background_image }} {{ form.background_image.errors|safe }}
					</div>  
				</div>	
				          
				<div class="form-actions">
	            	<button type="submit" class="btn primary">Create site</button>  
				</div>
				
			</form>                
		</div>
	</div>
{% endblock %}

socketjet_web/dashboard/templates/sites_edit.html
{% extends 'dashboard_base.html' %}

{% block main_content %}
	<div class="row">
		<div class="span12"> 
            <ul class="breadcrumb">
				<li><a href="/dashboard/sites/">List sites</a> <span class="divider">/</span></li>
				<li class="active"><strong>Edit site</strong></li>
			</ul>
			
			<h2 class="page-header">Edit Site</h2>
			<div class="alert alert-error">
				<a class="close" data-dismiss="alert">&times;</a>
				<strong>Warning!</strong>
				Changing the site name will also change your subdomain name.
			</div>

			<form action="." method="POST" class="form-horizontal">{% csrf_token %}
				<div class="control-group {% if form.site_prefix.errors %}error{% endif %}">
	               	<label for="id_site_prefix">{{ form.site_prefix.label }}</label>
					<div class="controls">
						{{ form.site_prefix }} 
						{{ form.site_prefix.errors|safe }}
					</div>  
				</div>  
				
				<div class="control-group">
	               	<label for="id_api_key">API Key</label>
					<div class="controls">
						<p style="padding-top: 5px">{{ site.api_key }}</p>
					</div>  
				</div>
				
				<div class="control-group">
	               	<label for="id_secret_key">Secret Key</label>
					<div class="controls">
						<p style="padding-top: 5px">{{ site.secret_key }}</p>
					</div>  
				</div>
				
				<div class="control-group">
	               	<label for="id_created">Created date</label>
					<div class="controls">
						<p style="padding-top: 5px">{{ site.created|date:'M jS Y' }}</p>
					</div>  
				</div>
				
				<div class="form-actions">
	            	<button type="submit" class="btn primary">Save changes</button>  
				</div>
				
			</form>                
		</div>
	</div>
{% endblock %}

socketjet_web/dashboard/templates/sites_list.html
{% extends "dashboard_base.html" %}

{% block script %}
	{{ block.super }}
	<script type="text/javascript">  
		$(document).ready(function() {
			$('.delete').click(function() {    
				$('#del_btn').attr('href', '/dashboard/sites/delete/' + this.id + '/');
				$('#delete-modal').modal('show');
				return false;
			});
		});
	</script>
{% endblock %}
                                 
{% block main_content %}
	
	<div class="row">
		<div class="span12"> 
			{% if messages %}
				{% for message in messages %}
				 	<div class="alert alert-success">
						<a class="close" data-dismiss="alert">&times;</a>
						<strong>Success!</strong>
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			
			<h2 class="page-header">Sites</h2>
			<a href="/dashboard/sites/add/" class="btn"><i class="plus"></i> Add new site</a>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Site Name</th>
						<th>Api Key</th>
						<th>Messages (daily avg*)</th>
						<th>Connections (daily avg*)</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for a in accounts %}
					<tr>
						<td>{{ a.site_prefix }}</td>
						<td>{{ a.api_key }}</td> 
						<td>{{ a.messages }}</td>
						<td>{{ a.connections }}</td>
						<td><a href="{% url sites_edit a.id %}">edit</a>&nbsp;&nbsp;
							<a href="" class="delete" id="{{ a.id }}">delete</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			<p><small>* Daily average over 30 days</small></p>                                     
		</div>
	</div>    
	
	<div class="modal fade hide" id="delete-modal">
	  <div class="modal-header">
	    <a class="close" data-dismiss="modal">×</a>
	    <h3>Are you sure you want to delete this site?</h3>
	  </div>
	  <div class="modal-body">
	    <p>This site will be inaccessible to you and your users. It will be disabled for 30 days and 
		then automatically deleted. Click 'Delete site' below if you're sure, you won't get any further confirmations.</p>
	  </div>
	  <div class="modal-footer">
	    <a href="#" class="btn danger" id="del_btn">Delete site</a>
	    <a href="#" class="btn" data-dismiss="modal">Close</a>
	  </div>
	</div>
{% endblock main_content %}